#!/usr/bin/env node
/**
 * Regenerate the desktop icon set and the favicon.
 *
 *     npm run generate-icons
 *
 * TWO SOURCES
 *
 * APP_ICON set in project.config.sh: the icon is DRAWN from that Lucide icon
 * (https://lucide.dev, the same names as `<Icon kind=...>`), on a rounded
 * square of APP_ICON_BACKGROUND (one colour, or two for a top-to-bottom
 * gradient), stroked in APP_ICON_FOREGROUND at APP_ICON_STROKE on Lucide's
 * 24-unit grid. The drawing comes from the lucide-static package. Every
 * output is produced from SVG, so nothing else needs installing, and the
 * favicon (web/favicon.svg) and resources/AppIcon.svg are written too.
 *
 * APP_ICON empty: resources/AppIcon.png is the source, square, 1024x1024, with
 * transparency, and with the artwork FILLING the canvas edge to edge. This
 * path needs ImageMagick for the macOS inset below (`brew install
 * imagemagick`), and stops before changing anything without it.
 *
 * WHY THERE ARE TWO PASSES
 *
 * macOS does not want a full-bleed icon. Since Big Sur every app icon is the
 * same rounded square drawn inside a canvas with a margin, and the Dock, the
 * Finder and Launchpad all lay icons out assuming that margin is there. Hand
 * macOS a full-bleed image and it is drawn at the full tile size, so it looms
 * over every neighbour in the Dock. The icon is not too large, it is missing
 * its margin.
 *
 * Apple's grid for a 1024pt canvas puts the artwork in the middle 824pt, which
 * is the 80.5% below. Windows and Linux have no such rule and want the
 * artwork full-bleed, so they keep the original.
 *
 * So: one pass produces everything from the full-bleed source, a second
 * produces only icon.icns from an inset copy, and that .icns replaces the one
 * from the first pass. A drawn icon simply draws its inset copy; a PNG one
 * needs ImageMagick to make it.
 */

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readConfig } from './config.mjs';
import { tool } from './tools.mjs';

const KIT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
// The project being built. npm runs scripts from the directory holding
// package.json, and the kit lives under lib/ inside it.
const root = process.cwd();

const SOURCE = path.join(root, 'resources', 'AppIcon.png');
const ICONS_DIR = path.join(root, 'src-tauri', 'icons');

/** Apple's icon grid: the artwork occupies the middle 824 of a 1024 canvas. */
const MACOS_CANVAS = 1024;
const MACOS_ARTWORK = 824;

function fail(message, ...details) {
    console.error(`\ngenerate-icons: ${message}`);
    for (const line of details) console.error(`  ${line}`);
    console.error('');
    process.exit(1);
}

function run(command, args, options = {}) {
    return execFileSync(command, args, { cwd: root, stdio: 'inherit', ...options });
}

/** The project's Tauri CLI, without npx. See tools.mjs. */
function tauri(args) {
    let command;
    try {
        command = tool(root, '@tauri-apps/cli', 'tauri');
    }
    catch (error) {
        fail(error.message);
    }
    return run(command[0], [command[1], ...args]);
}

function has(command) {
    try {
        execFileSync(command, ['--version'], { stdio: 'ignore' });
        return true;
    }
    catch {
        return false;
    }
}


/// Drawn from a Lucide icon

/**
 * The app icon as SVG: a rounded square of `background` with the Lucide
 * `glyph` centred on it, on a `size` canvas. `inset` draws it in Apple's
 * 824/1024 grid instead of edge to edge.
 */
function composeIcon({ glyph, background, foreground, stroke, size, inset, label }) {

    const tile = inset ? size * MACOS_ARTWORK / MACOS_CANVAS : size;
    const offset = (size - tile) / 2;
    const radius = tile * 0.225;

    // The drawing takes 56% of the tile: the proportion of Apple's own glyphs.
    const artwork = tile * 0.56;
    const scale = artwork / 24;
    const at = offset + (tile - artwork) / 2;

    const colors = background.trim().split(/\s+/);
    const gradient = colors.length > 1;
    const fill = gradient ? 'url(#background)' : colors[0];
    const defs = gradient
        ? `\n    <defs>\n        <linearGradient id="background" x1="0" y1="0" x2="0" y2="1">\n` +
          `            <stop offset="0" stop-color="${colors[0]}"/>\n` +
          `            <stop offset="1" stop-color="${colors[1]}"/>\n` +
          `        </linearGradient>\n    </defs>`
        : '';

    const n = v => Number(v.toFixed(3));
    return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}" width="${size}" height="${size}"` +
        (label ? ` role="img" aria-label="${label}"` : '') + `>\n` +
        `    <!-- Generated by npm run generate-icons from APP_ICON in project.config.sh. Do not edit. -->` +
        defs + `\n` +
        `    <rect x="${n(offset)}" y="${n(offset)}" width="${n(tile)}" height="${n(tile)}" rx="${n(radius)}" fill="${fill}"/>\n` +
        `    <g transform="translate(${n(at)} ${n(at)}) scale(${n(scale)})" fill="none" stroke="${foreground}"` +
        ` stroke-width="${stroke}" stroke-linecap="round" stroke-linejoin="round">\n` +
        `        ${glyph}\n` +
        `    </g>\n` +
        `</svg>\n`;

}

/** The shapes inside a lucide-static SVG, with its colour made explicit. */
function readGlyph(name, foreground) {

    const dir = path.join(root, 'node_modules', 'lucide-static', 'icons');
    if (!fs.existsSync(dir)) {
        fail('lucide-static is not installed, and the icon is drawn from it',
            '    npm install --save-dev lucide-static',
            '',
            'Nothing was changed.');
    }

    const file = path.join(dir, `${name}.svg`);
    if (!fs.existsSync(file)) {
        const names = fs.readdirSync(dir).filter(f => f.endsWith('.svg')).map(f => f.slice(0, -4));
        const stem = name.split('-')[0];
        const close = names.filter(n => n.includes(name) || n.startsWith(stem)).slice(0, 12);
        fail(`there is no Lucide icon named "${name}" (APP_ICON in project.config.sh)`,
            ...(close.length ? ['Close names: ' + close.join(', ')] : []),
            'Browse them at https://lucide.dev. Nothing was changed.');
    }

    const svg = fs.readFileSync(file, 'utf8').replace(/<!--[\s\S]*?-->/g, '');
    const inner = svg.slice(svg.indexOf('>', svg.indexOf('<svg')) + 1, svg.lastIndexOf('</svg>'));
    return inner
        .split('\n').map(line => line.trim()).filter(Boolean).join('\n        ')
        .replace(/currentColor/g, foreground);

}

/** Whether the icon font of the interface has this name too. */
function inIconFont(name) {

    const info = path.join(KIT, 'web', 'lucide-font', 'info.json');
    if (!fs.existsSync(info)) return true;
    return Object.prototype.hasOwnProperty.call(JSON.parse(fs.readFileSync(info, 'utf8')), name);

}

function fromLucide(config) {

    const name = config.APP_ICON;
    const options = {
        glyph: readGlyph(name, config.APP_ICON_FOREGROUND),
        background: config.APP_ICON_BACKGROUND,
        foreground: config.APP_ICON_FOREGROUND,
        stroke: config.APP_ICON_STROKE
    };

    if (!inIconFont(name)) {
        console.warn(`  warning: "${name}" is not in the icon font of the interface, so the title bar`);
        console.warn('  cannot show it. The desktop icons and the favicon are drawn all the same.');
    }

    const work = fs.mkdtempSync(path.join(os.tmpdir(), 'icons-'));
    try {
        const full = path.join(work, 'AppIcon.svg');
        const inset = path.join(work, 'AppIcon-macos.svg');
        const macIcons = path.join(work, 'icons-macos');
        fs.writeFileSync(full, composeIcon({ ...options, size: MACOS_CANVAS, inset: false }));
        fs.writeFileSync(inset, composeIcon({ ...options, size: MACOS_CANVAS, inset: true }));

        // Pass 1: everything, full-bleed.
        console.log(`  drawing the icon set from the Lucide icon "${name}"`);
        tauri(['icon', full]);

        // Pass 2: macOS only, from the inset drawing.
        tauri(['icon', inset, '-o', macIcons]);
        const icns = path.join(macIcons, 'icon.icns');
        if (!fs.existsSync(icns)) fail('the second pass produced no icon.icns');
        fs.copyFileSync(icns, path.join(ICONS_DIR, 'icon.icns'));
        console.log(`  icon.icns replaced with the version inset to ${MACOS_ARTWORK} on ${MACOS_CANVAS}`);

        // The source, kept where it can be seen and versioned, and the favicon,
        // so the browser tab always shows the same mark.
        fs.mkdirSync(path.join(root, 'resources'), { recursive: true });
        fs.copyFileSync(full, path.join(root, 'resources', 'AppIcon.svg'));
        fs.mkdirSync(path.join(root, 'web'), { recursive: true });
        fs.writeFileSync(path.join(root, 'web', 'favicon.svg'),
            composeIcon({ ...options, size: 64, inset: false, label: config.APP_PRODUCT_NAME }));
        console.log('  wrote resources/AppIcon.svg and web/favicon.svg');
    }
    finally {
        fs.rmSync(work, { recursive: true, force: true });
    }

}

/// From resources/AppIcon.png

function fromPng() {

    if (!fs.existsSync(SOURCE)) {
        fail(`${path.relative(root, SOURCE)} is missing`,
            'Put a square 1024x1024 PNG with transparency there, artwork filling the canvas.');
    }

    const magick = has('magick') ? 'magick' : (has('convert') ? 'convert' : null);
    if (!magick) {
        fail('ImageMagick is not installed, and the macOS icon cannot be inset without it',
            '    brew install imagemagick        # macOS',
            '    sudo apt install imagemagick    # Debian or Ubuntu',
            '',
            'Nothing was changed. The icons already in src-tauri/icons are still valid.');
    }

    // Pass 1: everything, from the full-bleed source.
    console.log('  generating the icon set from resources/AppIcon.png');
    tauri(['icon', path.relative(root, SOURCE)]);

    // Pass 2: macOS only, from an inset copy.
    const work = fs.mkdtempSync(path.join(os.tmpdir(), 'icons-'));
    const inset = path.join(work, 'AppIcon-macos.png');
    const macIcons = path.join(work, 'icons-macos');

    try {
        console.log(`  insetting the artwork to ${MACOS_ARTWORK} on a ${MACOS_CANVAS} canvas for macOS`);
        run(magick, [
            SOURCE,
            '-resize', `${MACOS_ARTWORK}x${MACOS_ARTWORK}`,
            '-background', 'none',
            '-gravity', 'center',
            '-extent', `${MACOS_CANVAS}x${MACOS_CANVAS}`,
            inset
        ]);

        tauri(['icon', inset, '-o', macIcons]);

        const icns = path.join(macIcons, 'icon.icns');
        if (!fs.existsSync(icns)) fail('the second pass produced no icon.icns');
        fs.copyFileSync(icns, path.join(ICONS_DIR, 'icon.icns'));
        console.log('  icon.icns replaced with the inset version');
    }
    finally {
        fs.rmSync(work, { recursive: true, force: true });
    }

}

const config = readConfig(root, KIT);
if (config.APP_ICON) fromLucide(config);
else fromPng();

// Mobile is out of scope for this template, and `tauri icon` writes these
// every time. Dropping them keeps the repository to what it actually ships.
for (const dir of ['android', 'ios']) {
    const full = path.join(ICONS_DIR, dir);
    if (fs.existsSync(full)) {
        fs.rmSync(full, { recursive: true, force: true });
        console.log(`  removed the unused ${dir} icons`);
    }
}

console.log('\nIcons regenerated. Rebuild the desktop app to see them.\n');
